### ISSUE TITLE
Link to platform guidance on setting up GitHub is broken

### ISSUE THREAD

**Issue by katharinebreeze** [moj-analytical-services/IntroRTraining#21]
This link - https://moj-analytical-services.github.io/platform_user_guidance/using-github-with-r-studio.html
Should now be - https://moj-analytical-services.github.io/platform_user_guidance/github.html

**Comment by Thomas-Hirsch** [comment]
https://user-guidance.services.alpha.mojanalytics.xyz/github.html#using-github-with-the-platform is the new guidance

**Comment by aidanmews** [comment]
Merged in with #27
