### ISSUE TITLE
Review extra resources section

### ISSUE THREAD

**Issue by Thomas-Hirsch** [moj-analytical-services/IntroRTraining#22]
Would be good to review the further reading resources that are signposted. In particular:
- Remove link to Datacamp due to their #metoo scandal: https://shirinsplayground.netlify.com/2019/04/consider_data_camp/
- Add link to education.rstudio.com, particularly their interactive primers, which are pretty useful

**Comment by aidanmews** [comment]
Have revised section, removing the datacamp link as not free anymore
