### ISSUE TITLE
AP upgrade and updates to set up instructions

### ISSUE THREAD

**Issue by chloepugh** [moj-analytical-services/IntroRTraining#38]
We may need to replace `s3tools` with `botor` and update the set up instructions to make sure participants have `botor` installed.

Here's the AP guidance on setting up botor: https://user-guidance.services.alpha.mojanalytics.xyz/appendix/botor.html#content. It's slightly complicated by the fact that it needs renv to be set up.

Also on the new AP and in a new renv environment, it takes a long time to install tidyverse so could be worth adding that to the set up instructions.

**Comment by ms130** [comment]
s3tools has now been replaced with botor
