### ISSUE TITLE
Exercise 1.7.5

### ISSUE THREAD

**Issue by chloepugh** [moj-analytical-services/IntroRTraining#40]
This exercise involves using `?subset` to check what the `subset()` function does. This could be a bit confusing as later on we encourage participants to use `filter()` from dplyr instead and never make use of `subset()`. Could be worth considering removing that exercise or replacing `subset` with a function that gets used in the course - e.g. `?c` or `?sum`

**Comment by ms130** [comment]
This exercise has been removed
